# o projeto
name: 'poc_dbt_lakehouse'
version: '1.0.0'
profile: 'poc_dbt_lakehouse'  # tem que bater com o nome no profiles.yml

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]

clean-targets: ["target", "dbt_packages"] # o que o dbt vai limpar quando rodar o comando dbt clean

models:
  poc_dbt_lakehouse:
    staging:
      +materialized: view #bronze: barato, sempre reflete a fonte
    intermediate:
      +materialized: table #silver: idem, nada consome direto
    marts:
      +materialized: table #gold: o BI lê isso, tem que ser rápido